### ISSUE TITLE
Newer RedactorJS support

### ISSUE THREAD

**Issue by rudyryk** [TigorC/django-redactorjs#9]
Hi Igor! Do you intend to continue application support and development? I'm using RedactorJS with Django and I like your approach for integration.

New version of RedactorJS produces different DOM so we need another admin CSS for styles reset. This code seems to work basically, but I have't tested it heavily yet:

```css
/** Reset Django admin styles for WYSYWYG elements */
form .aligned .redactor-editor p { margin-left: 0; padding-left: 0; }
form .aligned .redactor-editor ul { margin-left: inherit; padding-left: inherit; }
form .form-row .redactor-box p,
form .form-row .redactor-box li,
form .form-row .redactor-box dt,
form .form-row .redactor-box dd { font-size: inherit; line-height: inherit; }
```
